[package]
name = "yaserde-examples"
version = "0.8.0"
authors = ["Marc-Antoine Arnaud <maarnaud@media-io.com>"]
license = "MIT"
edition = "2018"

[dependencies]
bitflags = "2.6.0"
sepserde = {version = "0.8.0", path = "../sepserde" }
xml-no-std = "0.8.3"
