[package]
name = "yaserde-examples"
version = "0.8.0"
authors = ["Marc-Antoine Arnaud <maarnaud@media-io.com>"]
license = "MIT"
edition = "2018"

[dependencies]
sepserde = {version = "0.8.0", path = "../sepserde" }
